var test = require('tape')
var pg = require('../lib/main');

test('Generate test', function(t) {
  t.plan(1)
  const pass = pg.generatePassword();
  t.equal(pg.validatePassword(pass), true, `Autogenerated password ${pass} is NZISM compliant`);
})