language: node_js
node_js:
  - "node"
  - 10
git:
  depth:
    1
script:
  - npm run coverage
  - alias nyc='./node_modules/.bin/nyc'
  - nyc npm test && nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls