language: node_js
node_js:
  - "node"
  - 17
  - 16
  - 14
  - 12
git:
  depth:
    1
before_script:
  - rm -rf ./node_modules package-lock.json
  - npm install
script:
  - alias nyc='./node_modules/.bin/nyc'
  - npm run coverage
  - nyc npm test && nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls